
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi1.final_201220165;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos {
  /* terminals */
  public static final int tpuntoycoma = 2;
  public static final int tcase = 29;
  public static final int tigual = 7;
  public static final int tllavecerrar = 70;
  public static final int targ = 68;
  public static final int tthrow = 55;
  public static final int tmas = 31;
  public static final int tor = 35;
  public static final int tllaveabrir = 3;
  public static final int treturn = 27;
  public static final int tfinally = 52;
  public static final int tif = 15;
  public static final int tpor = 4;
  public static final int tid = 48;
  public static final int tmenorigual = 41;
  public static final int toverride = 64;
  public static final int tbool = 11;
  public static final int tcadena = 49;
  public static final int tclase = 9;
  public static final int tsuper = 61;
  public static final int tmenos = 32;
  public static final int tpackage = 60;
  public static final int tmenor = 39;
  public static final int tdefault = 30;
  public static final int tmain = 66;
  public static final int tswitch = 20;
  public static final int tint = 10;
  public static final int tthis = 38;
  public static final int timport = 8;
  public static final int tbreak = 26;
  public static final int tfor = 17;
  public static final int textends = 62;
  public static final int tmayorigual = 42;
  public static final int tnative = 56;
  public static final int tmayor = 40;
  public static final int ttrue = 46;
  public static final int tnot = 36;
  public static final int tprotected = 24;
  public static final int tand = 34;
  public static final int tcoma = 37;
  public static final int tnull = 65;
  public static final int tpunto = 5;
  public static final int EOF = 0;
  public static final int tpublic = 23;
  public static final int twhile = 18;
  public static final int tfinal = 25;
  public static final int tdiv = 33;
  public static final int error = 1;
  public static final int tstring = 12;
  public static final int tthrows = 63;
  public static final int tcontinue = 53;
  public static final int telse = 16;
  public static final int tfalse = 45;
  public static final int tnew = 28;
  public static final int ttry = 57;
  public static final int tnumero = 47;
  public static final int tprivate = 22;
  public static final int tcatch = 58;
  public static final int tcaracter = 50;
  public static final int tdp = 21;
  public static final int tdo = 19;
  public static final int tiguala = 43;
  public static final int tparentesisabrir = 69;
  public static final int tdiferente = 44;
  public static final int timplements = 59;
  public static final int tdouble = 14;
  public static final int tinterface = 54;
  public static final int tabstract = 51;
  public static final int tparentesiscerrar = 6;
  public static final int tstatic = 67;
  public static final int tchar = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tpuntoycoma",
  "tllaveabrir",
  "tpor",
  "tpunto",
  "tparentesiscerrar",
  "tigual",
  "timport",
  "tclase",
  "tint",
  "tbool",
  "tstring",
  "tchar",
  "tdouble",
  "tif",
  "telse",
  "tfor",
  "twhile",
  "tdo",
  "tswitch",
  "tdp",
  "tprivate",
  "tpublic",
  "tprotected",
  "tfinal",
  "tbreak",
  "treturn",
  "tnew",
  "tcase",
  "tdefault",
  "tmas",
  "tmenos",
  "tdiv",
  "tand",
  "tor",
  "tnot",
  "tcoma",
  "tthis",
  "tmenor",
  "tmayor",
  "tmenorigual",
  "tmayorigual",
  "tiguala",
  "tdiferente",
  "tfalse",
  "ttrue",
  "tnumero",
  "tid",
  "tcadena",
  "tcaracter",
  "tabstract",
  "tfinally",
  "tcontinue",
  "tinterface",
  "tthrow",
  "tnative",
  "ttry",
  "tcatch",
  "timplements",
  "tpackage",
  "tsuper",
  "textends",
  "tthrows",
  "toverride",
  "tnull",
  "tmain",
  "tstatic",
  "targ",
  "tparentesisabrir",
  "tllavecerrar"
  };
}

